=== yairm210/Unciv/docs/Modders/schemas/CityStateTypes.schema.json
{
  "$id": "https://raw.githubusercontent.com/yairm210/Unciv/refs/heads/master/docs/Modders/schemas/CityStateTypes.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CityStateTypes",
  "description": "A list of city state types, including their bonuses and color information.",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "title": "Name",
        "description": "The name of the City State Type.",
        "examples": [
          "Cultured",
          "Maritime",
          "Mercantile",
          "Militaristic",
          "Religious"
        ]
      },
      "friendBonusUniques": {
        "$ref": "refs/Uniques.schema.json",
        "title": "Friend Bonus Uniques",
        "description": "List of unique abilities granted to major civilizations when friends with this city state"
      },
      "allyBonusUniques": {
        "$ref": "refs/Uniques.schema.json",
        "title": "Ally Bonus Uniques",
        "description": "List of unique abilities granted to major civilizations when allied to city state"
      },
      "startBias": {
        "type": "array",
        "items": {
          "type": "string",
          "examples": ["Avoid [Tundra]", "Avoid [Desert]", "Coast", "Grassland"]
        },
        "uniqueItems": true,
        "title": "Start Bias",
        "description": "Types of tiles where every city-state of this type is more likely to start. Merged with any per-nation startBias."
      },
      "color": {
        "$ref": "refs/Color.schema.json",
        "description": "RGB color of text in civilopedia",
        "default": [255, 255, 255]
      }
    },
    "required": ["name"],
    "additionalProperties": false
  }
}

=== yairm210/Unciv/android/assets/jsons/Civ V - Vanilla/CityStateTypes.json
[
    {
        "name": "Cultured",
        "friendBonusUniques": [
            "[+3 Culture] <before the [Medieval era]>",
            "[+6 Culture] <starting from the [Medieval era]> <before the [Industrial era]>",
            "[+13 Culture] <starting from the [Industrial era]>"
        ],
        "allyBonusUniques": [
            "[+6 Culture] <before the [Medieval era]>",
            "[+12 Culture] <starting from the [Medieval era]> <before the [Industrial era]>",
            "[+26 Culture] <starting from the [Industrial era]>"
        ],
        "color": [139, 96, 255]
    },
    {
        "name": "Maritime",
        "friendBonusUniques": ["[+2 Food] [in capital]"],
        "allyBonusUniques": ["[+2 Food] [in capital]", "[+1 Food] [in all cities]"],
        "startBias": ["Coast"],
        "color": [56, 255, 112]
    },
    {
        "name": "Mercantile",
        "friendBonusUniques": [
            "[+2 Happiness] <before the [Medieval era]>",
            "[+3 Happiness] <starting from the [Medieval era]>"
        ],
        "allyBonusUniques": [
            "[+2 Happiness] <before the [Medieval era]>",
            "[+3 Happiness] <starting from the [Medieval era]>",
            "Provides a unique luxury"
        ],
        "color": [255, 216, 0]
    },
    {
        "name": "Militaristic",
        "friendBonusUniques": ["Provides military units every ≈[20] turns"],
        "allyBonusUniques": ["Provides military units every ≈[17] turns"],
        "color": [255, 0, 0]
    },
    {
        "name":"Religious",
        "friendBonusUniques":  [
            "[+3 Faith] <before the [Medieval era]>",
            "[+6 Faith] <starting from the [Medieval era]> <before the [Industrial era]>",
            "[+13 Faith] <starting from the [Industrial era]>"
        ],
        "allyBonusUniques":  [
            "[+6 Faith] <before the [Medieval era]>",
            "[+12 Faith] <starting from the [Medieval era]> <before the [Industrial era]>",
            "[+26 Faith] <starting from the [Industrial era]>"
        ],
        "color": [255, 255, 255]
    }
]
