=== yairm210/Unciv/docs/Modders/schemas/specialists.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": { "type": "string" },

            "production": { "type": "number" },
            "food": { "type": "number" },
            "gold": { "type": "number" },
            "science": { "type": "number" },
            "culture": { "type": "number" },
            "happiness": { "type": "number" },
            "faith": { "type": "number" },

            "color": { "$ref": "https://raw.githubusercontent.com/yairm210/Unciv/master/docs/Modders/schemas/color.json" },

            "greatPersonPoints": {
                "type": "object",
                "additionalProperties": {
                    "type": "integer"
                }
            }
        },
        "required": ["name", "color"],
        "additionalProperties": false
    }
}

=== yairm210/Unciv/android/assets/jsons/Civ V - Vanilla/Specialists.json
[
	{
		"name":"Scientist",
		"science":3,
		"greatPersonPoints": {"Great Scientist":3},
		"color": [0,0,255]
	},
	{
		"name":"Merchant",
		"gold":3,
		"greatPersonPoints": {"Great Merchant":3},
		"color": [255,215,0]
	},
	{
		"name":"Artist",
		"culture":2,
		"greatPersonPoints": {"Great Artist":3},
		"color": [160,32,240]
	},
	{
		"name":"Engineer",
		"production":2,
		"greatPersonPoints": {"Great Engineer":3},
		"color": [139,69,19]
	}
]
